import { Product, User, Review } from '@/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'El Dokuma Makrame Duvar Süsü',
    description: '%100 pamuk iple yapılmış güzel el dokuma makrame duvar süsü. Her odaya bohem bir dokunuş katmak için mükemmel.',
    price: 299.99,
    images: [
      'https://images.pexels.com/photos/6195260/pexels-photo-6195260.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/6195261/pexels-photo-6195261.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Ev Dekorasyonu',
    sellerId: '101',
    sellerName: 'Sanat Atölyesi',
    tags: ['makrame', 'duvar süsü', 'bohem', 'pamuk'],
    materials: ['Pamuk ip', 'Ahşap çubuk'],
    dimensions: '60cm x 90cm',
    customizable: true,
    stock: 15,
    rating: 4.8,
    reviewCount: 23,
    featured: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Seramik Kahve Fincan Seti',
    description: '2\'li el yapımı seramik kahve fincanı seti. Benzersiz sır uygulaması ile her fincan tek ve özel.',
    price: 150.00,
    images: [
      'https://images.pexels.com/photos/1549200/pexels-photo-1549200.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1549201/pexels-photo-1549201.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Seramik',
    sellerId: '102',
    sellerName: 'Kil & Ruh',
    tags: ['seramik', 'kahve fincanı', 'çömlek', 'el yapımı'],
    materials: ['Seramik', 'Gıda güvenli sır'],
    dimensions: '10cm x 10cm x 10cm',
    customizable: false,
    stock: 8,
    rating: 4.9,
    reviewCount: 16,
    featured: false,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    title: 'Örgü Yün Atkı',
    description: 'Güzel örgü desenli lüks el örgüsü yün atkı. %100 merino yününden yapılmış, sıcaklık ve yumuşaklık için.',
    price: 250.00,
    images: [
      'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/7679721/pexels-photo-7679721.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Giyim',
    sellerId: '103',
    sellerName: 'Örgü Dünyası',
    tags: ['örgü', 'yün', 'atkı', 'sıcak'],
    materials: ['%100 Merino yünü'],
    dimensions: '20cm x 180cm',
    customizable: true,
    stock: 12,
    rating: 4.7,
    reviewCount: 31,
    featured: true,
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    title: 'Ahşap Kesme Tahtası',
    description: 'Sürdürülebilir sert ahşaptan yapılmış premium kesme tahtası. Benzersiz geometrik desen ve mineral yağ kaplaması.',
    price: 420.00,
    images: [
      'https://images.pexels.com/photos/4110404/pexels-photo-4110404.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/4110405/pexels-photo-4110405.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Mutfak',
    sellerId: '104',
    sellerName: 'Ahşap Sanatları',
    tags: ['ahşap', 'kesme tahtası', 'mutfak', 'sürdürülebilir'],
    materials: ['Akçaağaç', 'Mineral yağ'],
    dimensions: '30cm x 45cm x 4cm',
    customizable: true,
    stock: 6,
    rating: 4.9,
    reviewCount: 18,
    featured: false,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    title: 'Deri Çapraz Çanta',
    description: 'Ayarlanabilir askılı el yapımı deri çapraz çanta. Zamanla güzelce yaşlanan hakiki tam tahıl deriden yapılmış.',
    price: 630.99,
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1152078/pexels-photo-1152078.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Aksesuar',
    sellerId: '105',
    sellerName: 'Deri & Dantel',
    tags: ['deri', 'çapraz çanta', 'çanta', 'aksesuar'],
    materials: ['Tam tahıl deri', 'Pirinç aksesuar'],
    dimensions: '25cm x 20cm x 8cm',
    customizable: true,
    stock: 4,
    rating: 4.8,
    reviewCount: 25,
    featured: true,
    createdAt: new Date('2024-02-05'),
  },
  {
    id: '6',
    title: 'El Yapımı Sabun Koleksiyonu',
    description: 'Doğal malzemelerle yapılmış 3\'lü zanaat sabunu seti. Her sabun esansiyel yağlarla kokulu ve doğal boyalarla renkli.',
    price: 95.50,
    images: [
      'https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/4465125/pexels-photo-4465125.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Banyo & Vücut',
    sellerId: '106',
    sellerName: 'Saf Esans',
    tags: ['sabun', 'doğal', 'esansiyel yağ', 'el yapımı'],
    materials: ['Zeytinyağı', 'Hindistan cevizi yağı', 'Esansiyel yağlar'],
    dimensions: 'Her biri 8cm x 5cm x 3cm',
    customizable: false,
    stock: 20,
    rating: 4.6,
    reviewCount: 42,
    featured: false,
    createdAt: new Date('2024-02-10'),
  },
];

export const mockUser: User = {
  id: '1',
  email: 'ahmet.yilmaz@email.com',
  firstName: 'Ahmet',
  lastName: 'Yılmaz',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
  isSeller: false,
  createdAt: new Date('2024-01-01'),
};

export const mockReviews: Review[] = [
  {
    id: '1',
    userId: '1',
    userName: 'Elif Kaya',
    productId: '1',
    rating: 5,
    comment: 'Kesinlikle muhteşem! Kalitesi harika ve oturma odamda mükemmel görünüyor.',
    images: ['https://images.pexels.com/photos/6195262/pexels-photo-6195262.jpeg?auto=compress&cs=tinysrgb&w=400'],
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    userId: '2',
    userName: 'Mehmet Demir',
    productId: '2',
    rating: 5,
    comment: 'Bu fincanlar inanılmaz! İşçilik birinci sınıf ve elinizde harika hissettiriyor.',
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '3',
    userId: '3',
    userName: 'Ayşe Öztürk',
    productId: '3',
    rating: 4,
    comment: 'Güzel atkı, çok sıcak ve yumuşak. Örgü deseni çok hoş.',
    createdAt: new Date('2024-02-01'),
  },
];

export const categories = [
  'Tümü',
  'Ev Dekorasyonu',
  'Seramik',
  'Giyim',
  'Mutfak',
  'Aksesuar',
  'Banyo & Vücut',
  'Takı',
  'Sanat',
  'Oyuncak',
];